### ISSUE TITLE
test_update_size failing on Travis

### ISSUE THREAD

**Issue by k4nar** [onitu/onitu#125]
It seems to be only occurring with Python 3. Cf https://travis-ci.org/onitu/onitu/jobs/45124300, https://travis-ci.org/onitu/onitu/builds/45679926 and https://travis-ci.org/onitu/onitu/builds/45124297.

The weird part is:

```
[15:12:24] DEBUG: A: Notifying the Referee about 'test2' in folder dir
[15:12:24] DEBUG: B: Notifying the Referee about 'test2' in folder dir
```

I can't reproduce it.

**Comment by Khady** [comment]
I had the error with py27: https://travis-ci.org/onitu/onitu/jobs/44990857

**Comment by k4nar** [comment]
Another one with Python 3.4: https://travis-ci.org/onitu/onitu/jobs/46129765

**Comment by k4nar** [comment]
Again: https://travis-ci.org/onitu/onitu/jobs/46662051

Still no idea of what's going on. Maybe I should split the test in two in order to see if that helps.

**Comment by k4nar** [comment]
Ok, this one doesn't even make sense: https://travis-ci.org/onitu/onitu/jobs/46881833
B gets a chunk of size 3, then ask for another one, get an empty one and aborts.

**Comment by k4nar** [comment]
I don't see the error on Travis since 0289c08, I guess that fixed it. I still don't get where this error came from though.
