### ISSUE TITLE
Flickr driver creates folder multiple times.

### ISSUE THREAD

**Issue by wapiflapi** [onitu/onitu#143]
When uploading a bunch of photos to flickr and the target folder doesn't exist yet, the driver attempts to create it. Since this is done in parallel for the different photos and because flickr allows for it we end up with multiple folders with the same name.

**Reproduce:**
Sync flickr with local storage, start onitu with a large (10+) number of new photos in local storage that will be synchronized.

**Result:**
Often two folders will be created on flickr with the same name, one or two photos in one folder and all the others in the other. I suspect the first folder found with a matching name is used.

**Expected Behavior:**
Onitu shouldn't create two folders with the same name, we need to avoid the race condition.

**Comment by Scylardor** [comment]
Commit 98961e336aae0afd5ec735c98b9057b85e6a0723 is supposed to fix it.

Before the change, I reproduced the bug at first try. After the fix, I tried several times and never had the issue again.

I'm closing, please re-open if the bug shows up again.
