### ISSUE TITLE
Remove Watchdog

### ISSUE THREAD

**Issue by k4nar** [onitu/onitu#15]
Due to a lot of small issues with Watchdog (for example, we can't listen to a `IN_CLOSE_WRITE` on Linux), we should remove Watchdog and use system-dependent solution for each platform.

We should list here the solution for each platform :
- Linux: Inotify with [pyinotify](https://github.com/seb-m/pyinotify)
- Mac: FSEvents with [MacFSEvents](https://pypi.python.org/pypi/MacFSEvents).
- BSD: [libinotify](https://github.com/dmatveev/libinotify-kqueue) (in the ports of FreeBSD and NetBSD) with pyinotify, or a more 'bare-bone' solution with kqueue and kevent.
- Windows: ?

If you find a solution for each missing platform, please make a suggestion.

**Comment by k4nar** [comment]
For mac, we can use [MacFSEvents](https://pypi.python.org/pypi/MacFSEvents).

**Comment by Khady** [comment]
Watchdog give some links: 
- [pnotify](http://mark.heily.com/pnotify)
- [unison_fsmonitor](https://webdav.seas.upenn.edu/viewvc/unison/trunk/src/fsmonitor.py?view=markup&pathrev=471)
- [fsmonitor](http://github.com/shaurz/fsmonitor)
- [guard](http://github.com/guard/guard)
- [pyinotify](http://github.com/seb-m/pyinotify)
- [inotify](ools: http://github.com/rvoicilas/inotify-tools)
- [jnotify](http://jnotify.sourceforge.net/)
- [treewalker](http://github.com/jbd/treewatcher)
- [file](onitor: http://github.com/pke/file.monitor)
- [pyfilesystem](http://code.google.com/p/pyfilesystem)

**Comment by k4nar** [comment]
For BSD, we might be able to use Pyinotify with the addition of a dependency to [libinotify](https://github.com/dmatveev/libinotify-kqueue). Cf [this issue](https://github.com/seb-m/pyinotify/pull/64). It even seems to be working on Mac OS.
We should be able to do the same thing without any dependency, as Python expose an API for kqueue and kevent. But I don't know if it worth all the work.

**Comment by k4nar** [comment]
@Khady : Unison's FSMonitor seems fine, I'll take a better look.
None of the other solution seems to be interesting (well, except pyinotify of course).

**Comment by k4nar** [comment]
LocalStorage now uses Pyinotify.

Next step would be Mac, but I don't have a Mac OS machine. Could somebody try to implement a watcher using MacFSEvent ? The API seems rather close to Pyinotify, it shouldn't be a problem.

**Comment by Khady** [comment]
We have the same problem with MacFSEvent than with Watchdog, the results of the tests are not very good. I don't think that we can easily expect a result as good as linux.

**Comment by k4nar** [comment]
I think we can, at some extent at least. I think that on systems not supporting `IN_CLOSE_WRITE`, LocalStorage should put the event in the queue, merge them, and process the ones that haven't changed in the last past X seconds.
It would slow things down, but we would trigger less events for incremental changes.

For OSX, I think you should take a deeper look at [rb-fsevent](https://github.com/thibaudgg/rb-fsevent) which is the library used by Listen. All I know is that it's what Guard is using, and it works pretty well on OSX.

**Comment by k4nar** [comment]
I think we can close it now and open a new ticket for OSX.
