### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Khady** [onitu/onitu#18]
We have to pick a license for the project.

| Library | Licence |
| --- | --- |
| circus | Apache License v2 |
| pyzmq | LGPLv3 + 3-clause BSD |
| redis | MIT |
| simplejson | MIT |
| logbook | BSD |
| path.py | MIT |
| sh | MIT |
| codespeed-client | MIT |
| pyinotify | MIT |
| MacFSEvents | BSD |

**Comment by Khady** [comment]
What kind of license do you prefer? Like the GPL or a more permissive one like the MIT/BSD?

**Comment by k4nar** [comment]
I would go with the GPL. BSD-like licences are good for libraries, but as we're making a software I think we should be free according to the terms of the Free Software Foundation.

**Comment by entwanne** [comment]
I would instead chose a _BSD_ license or another non-restrictive one.
Why would we want to prevent non-free use of _Onitu_ ?

**Comment by Khady** [comment]
Political position. I want to defend free software. Not open source.

**Comment by k4nar** [comment]
@entwanne what do you call a non-free use ? I still think that GPL would be the best choice, mostly for political reasons.

**Comment by entwanne** [comment]
If someone wants to add closed-source drivers for example ?

**Comment by k4nar** [comment]
I don't see any issue with that. Each driver can have a separate license.

**Comment by k4nar** [comment]
I think we should take a decision for that. I'm still in favor of the GPL.

**Comment by kolyne-dev** [comment]
It's maybe a stupid question but if a driver import the plug if the plug is gpl, the driver become gpl no ? So the lgpl is better if we want the possibility to have close source license driver.

**Comment by k4nar** [comment]
I don't think that's true, because you can see the Plug as a dependency. Like a Linux module.

**Comment by kolyne-dev** [comment]
Hum True. I thought about glibc which are in lgpl and for me onitu is in the same case than glibc. But if we compare onitu with linux kernel, i understand.

**Comment by k4nar** [comment]
Well, Onitu isn't a library, but it's a software which can be extended using an API. Like Inkscape or Blender (only with less fame ;)).

**Comment by entwanne** [comment]
I'm still in favor of the BSD :)

**Comment by Khady** [comment]
I'm in favor of the GPL, to defend the user and not the code.
But I'm OK with a MIT or LGPL license.

@azokal We don't compile the code and deliver an unique binary, so the linking part of the gpl doesn't apply for us (as far as I know, I asked a few people about this issue). We just load the code.

**Comment by k4nar** [comment]
I don't think that LGPL is be a good idea (it's clearly directed towards libraries). But I'm ok with MIT or BSD.

**Comment by entwanne** [comment]
I'm also ok with MIT or (L)GPL, so maybe MIT is the best compromise.

**Comment by k4nar** [comment]
We should really discuss that when we meet. This is a rather important issue, and we should take a decision before publishing any release.

**Comment by Khady** [comment]
The MIT seems to be the best compromise.

**Comment by k4nar** [comment]
Ok for MIT (as agreed in our last meeting).
