### ISSUE TITLE
Checksum fail in test_crash on Travis

### ISSUE THREAD

**Issue by k4nar** [onitu/onitu#20]
We had several checksum fails on Travis with test_crash lately. It's always on `test_crash_rep2_to_rep1` : 
- https://travis-ci.org/onitu/onitu/jobs/20893786
- https://travis-ci.org/onitu/onitu/jobs/20893994
- https://travis-ci.org/onitu/onitu/jobs/20858559
- https://travis-ci.org/onitu/onitu/jobs/20849385

There is also a TimeoutError, but I think that's less important : https://travis-ci.org/onitu/onitu/jobs/20858836

**Comment by k4nar** [comment]
I didn't see any checksum errors recently, but we still have a few TimeoutError (https://travis-ci.org/onitu/onitu/jobs/22184067).

**Comment by k4nar** [comment]
A new checksum error : https://travis-ci.org/onitu/onitu/jobs/23303478

Didn't have any time to investigate yet.

**Comment by Khady** [comment]
One more https://travis-ci.org/onitu/onitu/jobs/23902815

**Comment by k4nar** [comment]
I think it's linked to this commit : https://github.com/onitu/onitu/commit/15354bafaaf487c70b4a2fe4ae0aaacb4442de0d
I'll try to find why 1-byte chunks could cause an issue.

**Comment by k4nar** [comment]
It might be related to https://github.com/onitu/onitu/commit/a20573746949a5fe1507fdd9c9cc2ff419860dcb, as we're always appending to the file, ignoring the `offset` argument. I'm trying to see if seeking to the right offset cause any trouble.
