### ISSUE TITLE
Update the benchmarks

### ISSUE THREAD

**Issue by k4nar** [onitu/onitu#30]
The benchmarks are not up-to-date. Many things have changed in the testing suite.

**Comment by Khady** [comment]
Actually the benchmarks don't depend on the testing suite. They just use a common approach to manage onitu and to interact with the file system.

**Comment by k4nar** [comment]
Well, they just use basically all the utility functions from the functional tests :D .

**Comment by Khady** [comment]
fix in b5a851e087b
