### ISSUE TITLE
Refactor test_multipart

### ISSUE THREAD

**Issue by k4nar** [onitu/onitu#32]
The current implementation of `test_multipart` is bad in so many ways. It should use small chunks (size 1 for instance) and check that the transfer is aborted after each change, and that the file is consistent in the end.

**Comment by entwanne** [comment]
It seems to be OK with the new `test_multipart_copy`.

**Comment by k4nar** [comment]
Actually the test isn't ok. You set `chunk_size=1` in the source driver, but it's the target driver which choose the chunk size for the transfer. Also, 100KB is far too much with chunks of 1.
Corrected in 752480a.
