### ISSUE TITLE
Use OAuth2 for the API

### ISSUE THREAD

**Issue by k4nar** [onitu/onitu#34]
The API should only be accessible when connected via OAuth2.

A lot of Python libraries exist for OAuth, but I don't think that one of them really stands out. We should look for the best solution at the moment (I think it might be this one : https://github.com/idan/oauthlib/)

**Comment by wapiflapi** [comment]
Oauth2 looked complicated. It was decided to implement a simpler authentication mechanism as the need for delegation and use by third parties isn't clear (yet). The simpler version of the authentication was merged in #134.
