### ISSUE TITLE
Add a `setup.py`

### ISSUE THREAD

**Issue by k4nar** [onitu/onitu#4]
http://pythonhosted.org/an_example_pypi_project/setuptools.html

Onitu should be uploaded to Pypi at the release of the 0.1.

**Comment by Scylardor** [comment]
From a driver point of view : should we use a setup.py per driver ?

This could be especially useful for drivers with extra requirements. For example, the S3 driver requires `requests` and `futures`, and it would be silly to add them to the project's general requirements if the user doesn't use S3.

**Comment by Khady** [comment]
Should web use distribute, setuptools, distutils or Distutils2 ?

**Comment by Khady** [comment]
Setuptools.

http://stackoverflow.com/questions/6344076/differences-between-distribute-distutils-setuptools-and-distutils2/14753678#14753678
https://python-packaging-user-guide.readthedocs.org/en/latest/index.html

**Comment by k4nar** [comment]
Fixed by #100 .
