### ISSUE TITLE
Error with redis/ZMQ (invalid port)

### ISSUE THREAD

**Issue by entwanne** [onitu/onitu#5]
The problem happens when I try to launch Onitu with two local drivers, and one client. I use Python 2.7.5.

When I manually write in a file of the client software, the file is well notified and the write event is relayed to the client driver.
Then, a `plug.update_file` is done by the driver (`onitu/drivers/client/client.py`), but it throws an exception:

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "onitu/api/worker.py", line 57, in _get_file
    dealer.connect('tcp://localhost:{}'.format(port))
  File "socket.pyx", line 461, in zmq.backend.cython.socket.Socket.connect (zmq/backend/cython/socket.c:3976)
ZMQError: Invalid argument
```

We had noticed that a port was set to `None` when taking it from redis (`self.redis.get('drivers:{}:router'.format(driver))` on `onitu/api/worker.py:56`), but when we launch redis manually, the value is correctly set.
So, maybe a thread/process is launched too early, and the value is not set yet.

**Comment by k4nar** [comment]
I don't think it's any kind of race condition as it happens after everything has been started. It's definitively related to the client driver as it never happens with any other driver. I will investigate.

**Comment by k4nar** [comment]
Ok, I reproduce.
