### ISSUE TITLE
Add tests for the REST API

### ISSUE THREAD

**Issue by Khady** [onitu/onitu#70]
How can we build tests for the REST API? Maybe with unit tests instead of functional tests?
Do you know some tools?

**Comment by Khady** [comment]
I add a few tests in 8006755ea with requests to query the API.

**Comment by k4nar** [comment]
Well, I'm pretty sure that a "functional" approach would be better. You could either hardcode the response and compare, or seek for certain patterns or elements in the response.

**Comment by Khady** [comment]
I wrote a few functional tests for half of the API. I use requets to query the rest api. It works pretty well, but if you can check that I did no mistake...

It's pretty annoying to write unit tests because I have to setup an instance of onitu and escalator. And the results of the functional tests should be very close to the unit tests.

**Comment by Khady** [comment]
I finished the tests for the monitoring. I have a strange error on travia that I don't understand.

I found no way to wait for the api to be launched, the message in the log is send before the call of the function run.

**Comment by k4nar** [comment]
Unfortunately I don't see any way to do something after Bottle's start. So yeah, a (small) sleep might be the best solution here.

**Comment by k4nar** [comment]
Closing it. I'll open a new issue for adding some tests later.
