### ISSUE TITLE
Create folders when downloading remote folders

### ISSUE THREAD

**Issue by Scylardor** [onitu/onitu#71]
I'm having this problem when I try to synchronize e.g. Amazon S3 or Dropbox with Local Storage with folders that exist on the cloud, but not on Local Storage.

Strictly speaking : on my computer I sync LocalStorage with S3. Everything coming from S3 will be put in the 'example/driver_a/' folder. The S3 root for Onitu is 'onitu/'. I create the 'onitu/' and 'onitu/folder/' folders on S3 (Onitu isn't started). I then put 'test' in 'onitu/folder/'.

Then I start Onitu, which tries to synchronize 'onitu/folder/test'. Since 'onitu/' is the name of the S3 root, it actually tries to create the local file 'example/driver_a/folder/test'.

But since the 'folder/' directory doesn't exist locally, it raises these errors : 

```
[2014-07-29 09:56] ERROR: A: An error occurred during the call of 'start_upload': Error creating file 'example/driver_a/folder/.test.onitu-tmp': [Errno 20] Not a directory: path(u'example/driver_a/folder/.test.onitu-tmp')
[2014-07-29 09:56] ERROR: A: An error occurred during the call of 'abort_upload': Error deleting file 'example/driver_a/folder/.test.onitu-tmp': [Errno 20] Not a directory: 'example/driver_a/folder/.test.onitu-tmp'
```

We need to manage this. Note that the issue isn't always the other way around. For example, if I upload 'dir1/dir2/dir3/test' on S3, since S3 doesn't really have a file tree, it is OK if the folders dir1, dir2 and dir3 don't exist there. Maybe it'll need to be handled individually, since all drivers may not deal simply with it.

**Comment by k4nar** [comment]
We already handle new dirs in LocalStorage, we even have a test for it. The code to do it is the following : 

``` python
tmp_file.dirname().makedirs_p()
```

I think this is the only line which could throw an Errno 20, and I don't see why it would. The fact that it  fails with `example/driver_a/folder/.test.onitu-tmp` and not `example/driver_a/folder/` imply that `dirname` failed, but I don't understand why.

**Comment by k4nar** [comment]
Is it still an issue @Scylardor ? I'm pretty sure that LocalStorage works as expected for that.

**Comment by Scylardor** [comment]
Well, I still have the problem.

I just checked with the Dropbox driver and I had the exact same issue : 

```
[2014-09-14 18:58] INFO: A - Dealer: Starting to get 'dropbox/pouet' from dropbox
[2014-09-14 18:58] DEBUG: A - Dealer: Waiting for ROUTER port for dropbox
[2014-09-14 18:58] DEBUG: A - Dealer: Got ROUTER port for dropbox
[2014-09-14 18:58] DEBUG: A - Dealer: Connected
[2014-09-14 18:58] INFO: A - Dealer: Transfer of 'dropbox/pouet' from dropbox successful
[2014-09-14 18:58] ERROR: A: An error occurred during the call of 'start_upload': Error creating file 'example/driver_a/dropbox/pouet/.lm2.doc.onitu-tmp': [Errno 20] Not a directory: path(u'example/driver_a/dropbox/pouet/.lm2.doc.onitu-tmp')
```

The problem precisely is that we don't have a concept such as directories.
As for Dropbox, directories are just 0-sized files (like, IIRC, for Amazon S3), and here's what happens: 
- Onitu downloads a 0-size file called 'pouet' (in fact, the directory)
- Onitu tries to download 'pouet/lm2.doc', but fails, because on the local system pouet is a regular 0-size file, not a directory.

On the other hand, I think it would work if we would just ignore the file notification of directories. But I don't think ignoring all 0-size files is a good solution. I'm going to look for better ones...

**Comment by k4nar** [comment]
Ok, so it has nothing to do with LocalStorage.

This is a pretty serious issue. Adding directories to Onitu's structure won't change anything, as the point here is that you can't separate a file from a directory on some platforms. We have to find a solution.

**Comment by Scylardor** [comment]
With Dropbox, the solution is pretty simple : dropbox's file metadatas include a 'is_dir' boolean which will allow us to discard the detected files that actually are directories.

How ever there is no such feature with e.g. Amazon S3 (AFAIK). I think the most feasible thing would be to ignore 0-size files (after all, if they're empty, is it really important that they don't get transferred ?)...

**Comment by k4nar** [comment]
I don't really mind not detecting empty files on S3. Does S3 even handle that ?

**Comment by Scylardor** [comment]
Well, S3 hasn't any concept of directory either. Their file tree is totally virtual, which means for example you can have /root/test/pouet in your S3 bucket without even having a directory called 'test' in it !

But it still lists all files, even the empty ones (including the directories, but you haven't any way to know which are directories and which are empty regular files). I think that we can figure it out by, when detecting a zero-size object, see if its name serves as prefix for other files (i.e. it's a directory and we don't have to notify it).

In all cases, it will be pretty complex...

**Comment by k4nar** [comment]
Ignoring empty files seems to be the saner choice here.

**Comment by k4nar** [comment]
@Scylardor : Is it fixed somehow ?

**Comment by Scylardor** [comment]
As far as I'm concerned I think this is fixed.

On Dropbox the fix was easy.

On S3, the main change is that if we find an empty file in the change checking thread, we search for files with names beginning with this file's name + '/' (meaning it's a folder containing things). The folder file (not the files in it, of course) is skipped if there are files in it. Otherwise it is considered a regular empty file and is detected as is.

Since then I don't have the problem anymore with these drivers. Not sure about the other ones though.

**Comment by k4nar** [comment]
Well, as long as we have a test for it I don't see the issue.
