### ISSUE TITLE
Dropbox and case-insensitiveness problems

### ISSUE THREAD

**Issue by Scylardor** [onitu/onitu#73]
I'm not sure how to address this problem so let's expose it here.

Dropbox is a case-insensitive system : for it, every filename is lowercase.

This mainly introduces case-conflict issues when for example trying to upload 'test', 'Test', 'TesT'... The last case-conflicting file will always be the only kept one, as Dropbox treats case-conflicting uploads as updates of the same file.

This of course introduces an asymmetry between Dropbox and us (we have 'test', 'Test', 'TesT' in Onitu, and only 'test' on Dropbox). We can disable the overwriting when finishing an upload, which, if a case-conflict occurs, renames the new file to make its name unique (it's something like 'test (1)'). The response of Dropbox allows us to know what name it has chosen for the file.

If we do that, we can avoid asymmetry, but this implies changing the name of the file on Onitu side (`move_file` ?).  FYI, if I recall correctly, when detecting such a case conflict, the official Dropbox client renames the file by adding "(Case Conflict)" at the end, and doesn't upload it until the user renames it to a non-case-conflicting name. So that wouldn't be a 'never-seen-before' approach.

I'm not sure this would be a working approach, nor is it possible to do so, so for the moment I'll keep the 'overwriting' way and hope the users know how Dropbox works and that they should avoid to mess with case conflicts with it.

A convenient page that lists all the case issues with Dropbox is [here](http://www.tandbergdata.com/knowledge-base/index.cfm/dropbox-folder-and-file-names-are-case-insensitive/). I'll re-list them here : 
- File  “Aaa.txt” and file: “aaa.txt” are created in the same folder 
- File “Ccc” and folder “ccc” are created in the same folder 
- Folder “ddd” and folder “DDD” are created in the same folder 
- Rename a file or folder from “EEE” to “eee”

**Comment by k4nar** [comment]
It could actually be a big issue for LocalStorage as well. For example, FAT32, VFAT and HFS+ are case insensitive (but case preserving).

I'm not sure of what would be the good behavior, each solution seems either bad or hacky.

**Comment by Khady** [comment]
We should find a solution or display a **BIG WARNING** to the user.

**Comment by Scylardor** [comment]
This is going to be one of my tasks of the week.

We only have to set overwrite=False on [this line](https://github.com/onitu/onitu/blob/develop/drivers/dropbox/onitu_dropbox/dropbox_driver.py#L121), and Dropbox will generate a non-case conflicting name on the fly.

The problem I can foresee with that solution is that it may generate a name already taken by another file, maybe on another service linked to Onitu. I'm not sure as to what it could lead us in case of such a problem, nor what can we really do about it (ask the plug if such file exists and keep trying to modify the name until it is unique ?).

**Comment by k4nar** [comment]
I think we should think about that matter beyond Dropbox. The same issue can appear on other services too.

**Comment by k4nar** [comment]
Fixed by 016608d2d91365408808715b9ed199f96c87cd12.
