### ISSUE TITLE
Google drive Driver

### ISSUE THREAD

**Issue by kolyne-dev** [onitu/onitu#80]
hi,
It's just a review about what i made these days:
-Driver architecture rework for more modularity
-Error Handling
After some handtest it's working.
But for the moment I didn't finish to:
-Recode test
-Move Handling
I can't finish delete detection on drive because i need to get the file list on onitu.

**Comment by k4nar** [comment]
Cool thanks. Deletion detection is not a big issue. Every driver is blocked on that, but we're not sure when it'll be ready (it relies on the new rules).

**Comment by k4nar** [comment]
Closing it, as we still have the main issue #28 for that.
