### ISSUE TITLE
Timeouts in the tests of the API

### ISSUE THREAD

**Issue by k4nar** [onitu/onitu#82]
I'm seeing a lot of timeouts in the tests of the API lately. I thought I had fixed that a few weeks ago.
- https://travis-ci.org/onitu/onitu/jobs/35019974
- https://travis-ci.org/onitu/onitu/jobs/35019423

There is also this bug which is pretty strange : 
- https://travis-ci.org/onitu/onitu/jobs/35020568

**Comment by Scylardor** [comment]
Hard to tell where they come from.

I just made a few minor changes on the API, and fixed some 500 Errors (the third bug seems really linked to that), but nothing else.

I ran the tests several times on my computer, but it didn't timeout (or another error) a single time.

**Comment by k4nar** [comment]
Ok, we'll see were it goes. Maybe it was nothing :) .

**Comment by k4nar** [comment]
Do we still have timeouts lately, or has it been fixed ?

**Comment by k4nar** [comment]
I don't see any timeout in past two weeks on develop, closing it.

**Comment by Khady** [comment]
It seems to work on travis. But we didn't change anything, so it's weird. I added some debug to track the problem in the future.
