### ISSUE TITLE
Add missing tests in the API

### ISSUE THREAD

**Issue by k4nar** [onitu/onitu#83]
Many important routes are not tested in the API (file listing, entries listing…). We really should have a set of functionnal tests for each of them.

**Comment by Khady** [comment]
If you mean the route `/files` for the file listing, I added a test in the commit 5ac435135

Is it enough?

**Comment by k4nar** [comment]
Well, are all the routes well tested ? I just took a quick look a the tests, but it doesn't seem so.

**Comment by Khady** [comment]
I mean, is it enough to test the file listing? I don't check all the informations that are send when we call `/files` because I can't call escalator to get the access to the metadata.

We should add tests for `/entries` and `/entries/<name>`.

**Comment by Khady** [comment]
Added 2 tests in 58833bc

All the routes are tested. We should now improve the tests.

**Comment by k4nar** [comment]
What could be improved ? I mean, except the failures we get on Travis.

**Comment by k4nar** [comment]
After taking a quick look to the tests, it still lacks some tests, like what happen if we try to get an entry which doesn't exists. If this behavior is not documented, we should document and implement it.
