### ISSUE TITLE
Specific driver for testing

### ISSUE THREAD

**Issue by entwanne** [onitu/onitu#98]
We currently have a strong dependency with _LocalStorage_ in the tests.
It is not really reliable because this driver can crash, or system events detection can be very slow.
Thus we need to develop a new driver just for testing, which stores files in memory and can simply be controlled by Onitu tests suit.

**Comment by k4nar** [comment]
This drivers should accept some options, like whether he uses chunked upload or not.

The main issue is that with the new architecture it's not that easy to add a driver without polluting the production environment (this driver should NOT be available in production).

**Comment by k4nar** [comment]
I have something working on this branch : https://github.com/onitu/onitu/tree/test_driver
It passes all tests (I tested it literally hundreds of times), but for the moment we can't customize the available handlers via env variables. I think we will add that later anyway, when we will refactor the tests.
